#!/usr/bin/env python3
"""Generate RGB565 pixel-RLE data for the external OSPI UI asset store."""

from __future__ import annotations

import pathlib
import re
import zlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "vision_CPU0" / "src" / "hardware"
OUTPUT = SOURCE_DIR / "ui_assets_rle.inc"
ASSETS = (
    ("competition_logo", SOURCE_DIR / "competition_logo_rgb565.inc"),
    ("robot_arm", SOURCE_DIR / "robot_arm_rgb565.inc"),
)


def read_byte_array(path: pathlib.Path) -> bytes:
    text = path.read_text(encoding="utf-8")
    body = text.split("{", 1)[1].split("};", 1)[0]
    return bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{1,2})", body))


def encode_rgb565_rle(data: bytes) -> bytes:
    if len(data) % 2:
        raise ValueError("RGB565 data length must be even")

    encoded = bytearray()
    pixel_index = 0
    pixel_count = len(data) // 2
    while pixel_index < pixel_count:
        byte_index = pixel_index * 2
        pixel = data[byte_index : byte_index + 2]
        run = 1
        while run < 255 and pixel_index + run < pixel_count:
            next_index = (pixel_index + run) * 2
            if data[next_index : next_index + 2] != pixel:
                break
            run += 1
        encoded.extend((run, pixel[0], pixel[1]))
        pixel_index += run

    return bytes(encoded)


def format_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t g_{name}_rgb565_rle[] = {{"]
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    sections = ["/* Generated by tools/generate_ui_assets.py. Do not edit. */", ""]
    for name, path in ASSETS:
        raw = read_byte_array(path)
        encoded = encode_rgb565_rle(raw)
        sections.extend(
            (
                f"#define UI_ASSET_{name.upper()}_RAW_SIZE ({len(raw)}U)",
                f"#define UI_ASSET_{name.upper()}_CRC32 (0x{zlib.crc32(raw) & 0xFFFFFFFF:08X}U)",
                format_array(name, encoded),
                "",
            )
        )
        print(f"{name}: {len(raw)} -> {len(encoded)} bytes")

    OUTPUT.write_text("\n".join(sections), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
